name: group_expense
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.13.5
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.16.0
  google_sign_in: ^4.4.4
  font_awesome_flutter: ^8.0.1
  flutter_auth_buttons: ^0.8.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/font/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/font/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/font/WorkSans-Medium.ttf

    - family: WorkSansItalic
      fonts:
        - asset: assets/font/WorkSans-Italic.ttf
